### ISSUE TITLE
Readme uses both npm and jspm

### ISSUE THREAD

**Issue by mk-pmb** [Hochfrequenz/aurelia-openui5-bridge#3]
Hi! Is there a special reason why you advise to use npm to install but jspm to run the tests? It's a bit confusing without explanation.

**Comment by JoschaMetze** [comment]
Hi,
thanks for reaching out to me. I've updated the readme to make the instructions a little bit more verbose. npm install is needed to install all the devDependencies (gulp, jspm, etc.). jspm install is needed to install all runtime dependencies for the library itself (e.g. aurelia). Thus both steps are required for compilation / test.

Kind regards
Joscha

**Comment by mk-pmb** [comment]
Looks good, thanks! :+1:
